"""ANP-06 meta-protocol negotiation (``anp.meta.negotiation.v1``).

Wire models and the error table for ``anp.negotiate``. This replaces nothing in
``anp.meta_protocol``, which implements the earlier message-embedded design and
is kept for existing users.
"""

from .errors import (
    AUTHORIZATION_REQUIRED,
    META_NEGOTIATION_ERRORS,
    MORE_INFORMATION_REQUIRED,
    NEGOTIATION_EXPIRED,
    NEGOTIATION_REJECTED,
    NO_MATCHING_INTERFACE,
    UNSUPPORTED_CANDIDATE_PROFILE,
    UNSUPPORTED_CONTENT_TYPE,
    UNSUPPORTED_NEGOTIATION_MODE,
    UNSUPPORTED_SECURITY_PROFILE,
    MetaNegotiationError,
    MetaNegotiationErrorCode,
    meta_negotiation_error,
)
from .models import (
    DEFAULT_NEGOTIATION_MODE,
    EXECUTION_MODES,
    JSONRPC_BINDING,
    META_NEGOTIATION_PROFILE,
    META_PROTOCOL_INTERFACE_TYPE,
    MODE_NATURAL_LANGUAGE_PROTOCOL_DRAFTING,
    MODE_STRUCTURED_SELECTION,
    NEGOTIABLE_OBJECTS,
    NEGOTIATE_METHOD,
    STATUS_ACCEPTED,
    STATUS_NEEDS_MORE_INFORMATION,
    STATUS_REJECTED,
    CallerCapabilities,
    ExecutionPlan,
    Intent,
    MetaProtocolInterface,
    NegotiateRequestBody,
    NegotiationConstraints,
    NegotiationResult,
    NegotiationSchemas,
    NegotiationStatus,
    SelectedPath,
)

__all__ = [
    "AUTHORIZATION_REQUIRED",
    "DEFAULT_NEGOTIATION_MODE",
    "EXECUTION_MODES",
    "JSONRPC_BINDING",
    "META_NEGOTIATION_ERRORS",
    "META_NEGOTIATION_PROFILE",
    "META_PROTOCOL_INTERFACE_TYPE",
    "MODE_NATURAL_LANGUAGE_PROTOCOL_DRAFTING",
    "MODE_STRUCTURED_SELECTION",
    "MORE_INFORMATION_REQUIRED",
    "NEGOTIABLE_OBJECTS",
    "NEGOTIATE_METHOD",
    "NEGOTIATION_EXPIRED",
    "NEGOTIATION_REJECTED",
    "NO_MATCHING_INTERFACE",
    "STATUS_ACCEPTED",
    "STATUS_NEEDS_MORE_INFORMATION",
    "STATUS_REJECTED",
    "UNSUPPORTED_CANDIDATE_PROFILE",
    "UNSUPPORTED_CONTENT_TYPE",
    "UNSUPPORTED_NEGOTIATION_MODE",
    "UNSUPPORTED_SECURITY_PROFILE",
    "CallerCapabilities",
    "ExecutionPlan",
    "Intent",
    "MetaNegotiationError",
    "MetaNegotiationErrorCode",
    "MetaProtocolInterface",
    "NegotiateRequestBody",
    "NegotiationConstraints",
    "NegotiationResult",
    "NegotiationSchemas",
    "NegotiationStatus",
    "SelectedPath",
    "meta_negotiation_error",
]
