from .did_wba import (
    ANP_MESSAGE_SERVICE_TYPE,
    VM_KEY_AUTH,
    VM_KEY_E2EE_AGREEMENT,
    VM_KEY_E2EE_SIGNING,
    build_agent_message_service,
    build_anp_message_service,
    build_group_message_service,
    compute_jwk_fingerprint,
    create_did_wba_document,
    create_did_wba_document_with_key_binding,
    extract_auth_header_parts,
    generate_auth_header,
    generate_auth_json,
    resolve_did_wba_document,
    resolve_did_wba_document_sync,
    verify_auth_header_signature,
    verify_auth_json_signature,
    verify_did_key_binding,
)
from .did_resolver import resolve_did_document, resolve_did_document_sync
from .did_wba_authenticator import DIDWbaAuthHeader
from .did_wba_verifier import DidWbaVerifier, DidWbaVerifierConfig, DidWbaVerifierError
from .device_manifest import (
    DEVICE_MANIFEST_TYPE,
    PROFILE_CORE_BINDING_V2,
    PROFILE_DIRECT_BASE_V2,
    PROFILE_DIRECT_E2EE_V2,
    PROFILE_GROUP_BASE_V2,
    PROFILE_GROUP_E2EE_V2,
    PROFILE_IDENTITY_DISCOVERY_V2,
    DeviceManifest,
    DeviceManifestEntry,
    DeviceManifestError,
    add_device_to_did_document,
    build_vnext_did_document,
    find_eligible_device,
    parse_device_manifest,
    remove_device_from_did_document,
    update_device_in_did_document,
    validate_device_manifest,
)
from .federation import (
    FederatedVerificationError,
    FederatedVerificationResult,
    verify_federated_http_request,
)
from .http_signatures import (
    build_content_digest,
    extract_signature_metadata,
    generate_http_signature_headers,
    verify_http_message_signature,
)

# Define what should be exported when using "from anp.authentication import *"
__all__ = [
    "VM_KEY_AUTH",
    "VM_KEY_E2EE_SIGNING",
    "VM_KEY_E2EE_AGREEMENT",
    "ANP_MESSAGE_SERVICE_TYPE",
    "build_anp_message_service",
    "build_agent_message_service",
    "build_group_message_service",
    "compute_jwk_fingerprint",
    "create_did_wba_document",
    "create_did_wba_document_with_key_binding",
    "resolve_did_wba_document",
    "resolve_did_wba_document_sync",
    "resolve_did_document",
    "resolve_did_document_sync",
    "generate_auth_header",
    "generate_auth_json",
    "verify_auth_header_signature",
    "verify_auth_json_signature",
    "verify_did_key_binding",
    "extract_auth_header_parts",
    "DIDWbaAuthHeader",
    "DidWbaVerifier",
    "DidWbaVerifierConfig",
    "DidWbaVerifierError",
    "DEVICE_MANIFEST_TYPE",
    "PROFILE_CORE_BINDING_V2",
    "PROFILE_IDENTITY_DISCOVERY_V2",
    "PROFILE_DIRECT_BASE_V2",
    "PROFILE_GROUP_BASE_V2",
    "PROFILE_DIRECT_E2EE_V2",
    "PROFILE_GROUP_E2EE_V2",
    "DeviceManifest",
    "DeviceManifestEntry",
    "DeviceManifestError",
    "parse_device_manifest",
    "validate_device_manifest",
    "find_eligible_device",
    "build_vnext_did_document",
    "add_device_to_did_document",
    "update_device_in_did_document",
    "remove_device_from_did_document",
    "FederatedVerificationResult",
    "FederatedVerificationError",
    "verify_federated_http_request",
    "build_content_digest",
    "generate_http_signature_headers",
    "verify_http_message_signature",
    "extract_signature_metadata",
]
